---
swagger: "2.0"
info:
  description: "API For LearningSpring Service"
  version: "v1"
  title: "learningSpring"
host: "localhost:8020"
basePath: "/learningSpring/"
tags:
- name: "Subject"
schemes:
- "http"
paths:
  v1/subject/create_subject:
    post:
      tags:
      - "Subject"
      summary: "createSubject"
      description: "存储科目"
      operationId: "createSubject"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/SubjectCreator"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JsonResultBoolean"
  v1/subject/find_by_id/{id}:
    get:
      tags:
      - "Subject"
      summary: "findById"
      description: "根据id查询"
      operationId: "findByPhase"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JsonResultSubject"
  v1/subject/get_subjects_by_page:
    post:
      tags:
      - "Subject"
      summary: "getSubjectsByPage"
      description: "科目分页"
      operationId: "getSubjectsByPage"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/PageRequestWrapper"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JsonResultPageSubjectVO"
  v1/subject/update_subject/{id}:
    post:
      tags:
      - "Subject"
      summary: "updateSubject"
      description: "更新科目"
      operationId: "updateSubject"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/SubjectUpdater"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JsonResultBoolean"
definitions:
  JsonResult:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      result:
        type: "object"
  JsonResultBoolean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      result:
        type: "boolean"
  JsonResultPageSubjectVO:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      result:
        $ref: "#/definitions/PageSubjectVO"
  JsonResultSubject:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      result:
        $ref: "#/definitions/Subject"
  Page:
    type: "object"
    properties:
      totalPages:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      number:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          type: "object"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      last:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      numberOfElements:
        type: "integer"
        format: "int32"
  PageRequestWrapper:
    type: "object"
    properties:
      pageNum:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
      bean:
        type: "object"
  PageSubjectVO:
    type: "object"
    properties:
      totalPages:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      number:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          $ref: "#/definitions/SubjectVO"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      last:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      numberOfElements:
        type: "integer"
        format: "int32"
  Pageable:
    type: "object"
    properties:
      offset:
        type: "integer"
        format: "int64"
      sort:
        $ref: "#/definitions/Sort"
      paged:
        type: "boolean"
      unpaged:
        type: "boolean"
      pageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
  Sort:
    type: "object"
    properties:
      sorted:
        type: "boolean"
      unsorted:
        type: "boolean"
  Subject:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      createdAt:
        type: "integer"
        format: "int64"
      updatedAt:
        type: "integer"
        format: "int64"
      version:
        type: "integer"
        format: "int32"
      subjectName:
        type: "string"
      phase:
        type: "integer"
        format: "int32"
      subjectCode:
        type: "string"
  SubjectCreator:
    type: "object"
    properties:
      subjectName:
        type: "string"
        description: "科目名称"
      phase:
        type: "integer"
        format: "int32"
        description: "学段"
      subjectCode:
        type: "string"
  SubjectUpdater:
    type: "object"
    properties:
      subjectName:
        type: "string"
        description: "科目名称"
      subjectCode:
        type: "string"
        description: "学科编码"
  SubjectVO:
    type: "object"
    properties:
      version:
        type: "integer"
        format: "int32"
        description: "数据版本"
      id:
        type: "integer"
        format: "int64"
        description: "主键"
      createdAt:
        type: "integer"
        format: "int64"
        description: "创建时间"
      updatedAt:
        type: "integer"
        format: "int64"
        description: "修改时间"
      subjectName:
        type: "string"
        description: "科目名称"
      phase:
        type: "integer"
        format: "int32"
        description: "学段"
